### ISSUE TITLE
JAWStats not able to read all Awstats files

### ISSUE THREAD

**Issue by mrpepik** [webino/JAWStats#14]
Hi,

I have many web sites that I have been asked to provide a web interface to review the stats on.  So I am pulling the stats from a database, then passing them through awstats.  I like the interface for JAWStats and want to use it to integrate in and make things in line with main site, but I am having a problem with all versions I have tried reading all of the log files.  

I am using awstats on Ubuntu version:  7.0~dfsg-7ubuntu1.

The scripts read all log files up to about June 2014 and then I get Naans for everything after like May or June of 2014.

Do you have a way I can debug or figure out why they are not reading properly?  I just reprocessed all my stats for one site and its having the same issue.

Thanks
MrPepik

**Comment by bacinsky** [comment]
Hi, did you enable error reporting? It's disabled by default in the index file, try comment it out https://github.com/webino/JAWStats/blob/a542428cf2bf0a9909591bac764e5aca7726d10c/index.php#L30

**Comment by mrpepik** [comment]
Hi Peter,

It turns out to be the way that AWStats is writing out log files after May 2014, even generating all the AWStats log files in a single run.  The later log files are being encoded as "ISO-8859 text" while the older log files are written as "ASCII text".  

By running the following on one of the ISO-8859 Encoded log files, I was able to see the information in the log file with JAWStats:  

iconv -c -t ASCII awstats012015.TEST.COM.txt > awstats012015.TEST.COM.txt2
mv awstats012015.TEST.COM.txt2 awstats012015.TEST.COM.txt

I am now investigating if there is a way to keep the AWStats log files as ASCII TEXT encoding only, or I will have to write the convert code above into a cron script.

Or do you know of a way to have JAWStats read the ISO-8859 encoded files?

Thanks for answering so quickly.

MrPepik
